### ISSUE TITLE
no-inline-comments ignore

### ISSUE THREAD

**Issue by romainquellec** [kentcdodds/prettier-eslint-atom#31]
Hi !

Got a classic package.json config like : 

`"eslintConfig": {
    "parser": "babel-eslint",
    "extends": "airbnb",`

plus `"no-inline-comments": 0,`

But still, my comments are not allowed to be inlined. I'm using react-boilerplate and they are a lot of code like this : 

`export class Map extends React.PureComponent { // eslint-disable-line react/prefer-stateless-function`

Do you have the same behavior ? Did I forget another rule ?

Thank you.

**Comment by kentcdodds** [comment]
So, prettier is responsible for moving your comments to a different line because that line is too long (see [here](https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20class%20Map%20extends%20React.PureComponent%20%7B%20%2F%2F%20eslint-disable-line%20react%2Fprefer-stateless-function%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)). So by the time eslint comes along to fix things, the code it's already on a newline and eslint isn't going to put it back. Even if you didn't have prettier, that line would result in a `max-len` linting error (unless you've disabled that rule).

So here's what I suggest. Instead of using `eslint-disable-line` use `eslint-disable-next-line` like [this](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20eslint-disable-next-line%20react%2Fprefer-stateless-function%5Cnexport%20class%20Map%20extends%20React.PureComponent%20%7B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D):

```javascript
// eslint-disable-next-line react/prefer-stateless-function
export class Map extends React.PureComponent {
}
```

I think that looks cleaner anyway :)

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this as there's nothing that can/should be done from this tool's perspective.
